#!/bin/bash

SCRIPTS_BASEDIR=~/Dropbox/Technical/Programming/shellScripts

KIT_BASEDIR=/opt/kits

TOMCAT_BASEDIR=/opt/tomcat
MAVEN_BASEDIR=/opt/maven
ECLIPSE_BASEDIR=/opt/eclipse

MAVEN_ARCHIVEDIR=$KIT_BASEDIR/maven
TOMCAT_ARCHIVEDIR=$KIT_BASEDIR/tomcat
ECLIPSE_ARCHIVEDIR=$KIT_BASEDIR/eclipse
SOLR_ARCHIVEDIR=$KIT_BASEDIR/solr

MAVEN_INSTANCEDIR=$MAVEN_BASEDIR/instances
TOMCAT_INSTANCESDIR=$TOMCAT_BASEDIR

